services:
  - type: web
    name: opciones-wall-street
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt || true"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
